# -*- coding: utf-8 -*-
"""fashion_mnist_reader.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TQ-UvjC-cdnH3p4FsIqMvNlNbrMe5b1_
"""

# Read Fashion MNIST dataset

import mnist_reader
X_train, y_train = mnist_reader.load_mnist('data/fashion', kind='train')
X_test, y_test = mnist_reader.load_mnist('data/fashion', kind='t10k')

# Your code goes here . . .